added files

diff --git a/.github/workflows/mainPipeline.yml b/.github/workflows/mainPipeline.yml
--- a/.github/workflows/mainPipeline.yml
+++ b/.github/workflows/mainPipeline.yml
@@ -23,13 +23,83 @@ jobs:
       - name: Run Tests
         run: |
            cd /home/runner/work/L00171125_Dissertationproject/L00171125_Dissertationproject/WWA-backend-master
-           npm run test
+           npm run test -- --coverage
       - name: Run Linter
         run: |
           cd /home/runner/work/L00171125_Dissertationproject/L00171125_Dissertationproject/WWA-backend-master
           npm install eslint --save-dev 
           npx eslint . --fix
+
+      - name: Quality Gate
+        run: |
+         COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
+         if [ $COVERAGE -lt 80 ]; then
+         echo "Code coverage too low: $COVERAGE%"
+          exit 1
+         fi
+         LINT_ERRORS=$(npx eslint . --max-warnings 0 || echo 1)
+         if [ $LINT_ERRORS -gt 0 ]; then
+          echo "Linting errors found."
+          exit 1
+         fi
          # npm install --save-dev prettier eslint-config-prettier eslint-plugin-prettier
+          
+# Snyk security scan step for web
+
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v2
+        with:
+          node-version: '20' 
+
+      - name: Install Snyk CLI
+        run: npm install -g snyk
+
+      - name: Snyk Security Scans
+        run: snyk test --org=abhi9705 --project-name='L00171125_Dissertationproject'
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        working-directory: WWA-backend-master
+
+      - name: Snyk Security Scan Frontend
+        run: snyk test --org=abhi9705 --project-name='L00171125_Dissertationproject'
+        continue-on-error: true
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        working-directory: WWA-frontend-master
+                
+      - name: Snyk Monitor
+        run: snyk monitor --org=abhi9705 --project-name='L00171125_Dissertationproject'
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        working-directory: WWA-backend-master
+
+      - name: Snyk Monitor Frontend
+        run: |
+         npm install --force
+         snyk monitor --org=abhi9705 --project-name='L00171125_Dissertationproject'
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+        working-directory: WWA-frontend-master
+                
+  # Snyk security scan step for Code Scanning
+
+      - name: Run Snyk to check for vulnerabilitie
+        uses: snyk/actions/node@master
+        continue-on-error: true
+        with:
+          args: ./WWA-backend-master --sarif-file-output=snyk.sarif
+        env:
+          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
+      - name: Upload SARIF to GitHub Security Center
+        uses: github/codeql-action/upload-sarif@v3
+        with:
+          sarif_file: snyk.sarif
+          category: 'Snyk OpenSource Unique Category'
+
 
 
   Build_docker_Images:
@@ -220,7 +290,6 @@ jobs:
 
   SonarCloudScan:
     runs-on: ubuntu-latest
-    needs: [snyk_analysis]
     steps:
       - name: Checkout code
         uses: actions/checkout@v4   
@@ -257,7 +326,6 @@ jobs:
 
   snyk_analysis:
     runs-on: ubuntu-latest
-    needs: [IAC_Build]
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
@@ -287,21 +355,21 @@ jobs:
         run: npm install -g snyk
 
       - name: Snyk Security Scans
-        run: snyk test --org=shreyashettys202 --project-name='Project-Group3'
+        run: snyk test --org=Abhi9705 --project-name='L00171125_Dissertationproject'
         continue-on-error: true
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         working-directory: WWA-backend-master
 
       - name: Snyk Security Scan Frontend
-        run: snyk test --org=shreyashettys202 --project-name='Project-Group3'
+        run: snyk test --org=Abhi9705 --project-name='L00171125_Dissertationproject'
         continue-on-error: true
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         working-directory: WWA-frontend-master
                 
       - name: Snyk Monitor
-        run: snyk monitor --org=shreyashettys202 --project-name='Project-Group3'
+        run: snyk monitor --org=Abhi9705 --project-name='L00171125_Dissertationproject'
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         working-directory: WWA-backend-master
@@ -309,7 +377,7 @@ jobs:
       - name: Snyk Monitor Frontend
         run: |
          npm install --force
-         snyk monitor --org=shreyashettys202 --project-name='Project-Group3'
+         snyk monitor --org=Abhi9705 --project-name='L00171125_Dissertationproject'
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         working-directory: WWA-frontend-master
