added files

diff --git a/.github/workflows/mainPipeline.yml b/.github/workflows/mainPipeline.yml
--- a/.github/workflows/mainPipeline.yml
+++ b/.github/workflows/mainPipeline.yml
@@ -196,12 +196,15 @@ jobs:
           for i in {1..2}; do
           echo "Running Chaos Engineering Experiment Iteration #$i"
           FIS_EXP_ID=$(aws fis start-experiment --experiment-template-id EXTBY5y1A6MqkfjXn --query 'experiment.id' --output text)
+          echo "FIS_EXP_ID=$FIS_EXP_ID"
           echo "FIS_EXP_ID=$FIS_EXP_ID" >> $GITHUB_ENV
 
+                    if [ -z "$FIS_EXP_ID" ]; then
+            echo "Failed to start FIS experiment. Exiting."
+            exit 1
+          fi
+
           echo "Start MTTR Scriptss" 
-          ls 
-          pwd
-          ls
           chmod +x ./measure_mttr.sh
           ./measure_mttr.sh $FIS_EXP_ID &
           echo "Wait for FIS Experiment to Complete"
