added files

diff --git a/.github/workflows/mainPipeline.yml b/.github/workflows/mainPipeline.yml
--- a/.github/workflows/mainPipeline.yml
+++ b/.github/workflows/mainPipeline.yml
@@ -44,11 +44,6 @@ jobs:
          path: /home/runner/work/L00171125_Dissertationproject/L00171125_Dissertationproject/WWA-backend-master/eslint-report.json
          if-no-files-found: warn
 
-      - name: Run Integration Tests
-        run: |
-          cd /home/runner/work/L00171125_Dissertationproject/L00171125_Dissertationproject/WWA-backend-master
-          npm run test:integration -- --coverage
-
       - name: Upload Unit Test Coverage Report
         uses: actions/upload-artifact@v2
         with:
@@ -208,35 +203,46 @@ jobs:
           for i in {1..2}; do
            echo "Running Chaos Engineering Experiment Iteration #$i"
            FIS_EXP_ID=$(aws fis start-experiment --experiment-template-id EXTBY5y1A6MqkfjXn --query 'experiment.id' --output text)
-           echo "FIS_EXP_ID=$FIS_EXP_ID"
-           echo "FIS_EXP_ID=$FIS_EXP_ID" >> $GITHUB_ENV
+          
+          
+            if [ -z "$FIS_EXP_ID" ]; then
+              echo "Failed to start experiment. Exiting."
+              exit 1
+            fi
+            echo "FIS_EXP_ID=$FIS_EXP_ID"
 
  
 
            echo "Start MTTR Scriptss" 
            chmod +x ./measure_mttr.sh
            ./measure_mttr.sh $FIS_EXP_ID &
+
+
             echo "Wait for FIS Experiment to Complete"
             INSTANCE_ID=i-0609b0b289067d17d
+
             INSTANCE_STATUS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].State.Name' --output text)
             echo "Current instance status: $INSTANCE_STATUS"
             FIS_EXP_ID=${{ env.FIS_EXP_ID }}
+           
             while true; do
-            STATUS=$(aws fis get-experiment --id "$FIS_EXP_ID" --query 'experiment.state.status' --output text)
-            echo "Current experiment status: $STATUS"
-            INSTANCE_STATUS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].State.Name' --output text)
-            echo "Current instance status: $INSTANCE_STATUS"
-            echo "----------------------------------------------"
-            if [ "$STATUS" == "completed" ]; then
-              break
-            elif [ "$STATUS" == "failed" ] || [ "$STATUS" == "stopped" ]; then
-              echo "Experiment $FIS_EXP_ID did not complete successfully. Status: $STATUS"
-              exit 1
-            fi
-            sleep 10
+              STATUS=$(aws fis get-experiment --id "$FIS_EXP_ID" --query 'experiment.state.status' --output text)
+              if [ -z "$STATUS" ]; then
+                echo "Failed to get experiment status. Exiting."
+                exit 1
+              fi
+              echo "Current experiment status: $STATUS"
+              INSTANCE_STATUS=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].State.Name' --output text)
+              echo "Current instance status: $INSTANCE_STATUS"
+              echo "-----------------------------------------------------------"
+              if [ "$STATUS" == "completed" ]; then
+                break
+              elif [ "$STATUS" == "failed" ] || [ "$STATUS" == "stopped" ]; then
+                echo "Experiment $FIS_EXP_ID did not complete successfully. Status: $STATUS"
+                exit 1
+              fi
+              sleep 10
             done
-
-            echo "dbsahbadbasnfbdafhbsdkfbdsakfdak f kjdasfdskbdkfbsdkfbdskfbdk"
 
             echo "Wait for EC2 Instance to Return to Running" 
             INSTANCE_ID=i-0609b0b289067d17d
